language: java
jdk:
  - openjdk10

script: "./gradlew clean build"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew cobertura coveralls

#docker
services:
  - docker


before_deploy:
  #- zip -r makingboard *
  - mkdir -p deploy
  - mkdir -p output
  - mv build/libs/makingboard.war output/makingboard.war
  - docker build -t giraffeb/makingboard .
  - docker save -o makingboard.tar

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: giraffeb-bucket # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true

    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: giraffeb/makingboad
      branch: master

notifications:
  email:
    recipients:
      - soulgoon@gmail.com