language: java
jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew jacocoTestReport coveralls
